### ISSUE TITLE
The auto post task crashes from HTTP Exceptions

### ISSUE THREAD

**Issue by Taarek** [top-gg/DBL-Python-Library#33]
This issue tracker is **ONLY** used for reporting bugs with __dblpy__. Feel free to share your suggestions in the #api channel in our [Discord server](https://discord.gg/EYHTgJX)!

For help with general Python issues, use [StackOverflow](https://stackoverflow.com), our [#development channel](https://discord.gg/EYHTgJX), or the [Python Discord server](https://discord.gg/python).

## Expected Behavior

The DBLClient._auto_post() task should not crash from HTTP Exceptions (503's)

## Current Behavior
If the client receives a 503 from top.gg when posting server count, it will not handle the status code and crash the task, requiring the user to reload their extensions.

## Development Environment

dblpy: 0.3.4
Python: 3.8.5
OS: Ubuntu 18.04.1

## Steps to Reproduce

1. Use the auto posting server count functionality with dblpy
2. Wait for a HTTP Exception to occur (most commonly a 503)
3. Observe how the task crashes and doesn't recover and you're left with inaccurate server count.

## Possible Solution

Just a try-except block is sufficient

## Possible Implementation

Something like:
```python
try:
    ...
except HTTPException:
    pass
```

Would work fine because it will just re-try reposting in 30 minutes, so it doesnt spam pointless requests if the service is entirely offline.

**Comment by shivaco** [comment]
Ideally, I would prefer to use a separate exception type for response codes greater than or equal to 500, which would then be raised in the `request` function and handled in the autopost.
